language: node_js
node_js:
- '10'
- '12'
install:
- npm install
- wget https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_0.54.0_Linux-64bit.deb
- sudo dpkg -i hugo*.deb
script:
- npm run production
- hugo
deploy:
  local-dir: public
  repo: osdforum/osdforum.org
  target-branch: gh-pages
  provider: pages
  keep-history: true
  skip-cleanup: true
  github_token: "$GITHUB_TOKEN"
  email: chris.guindon@eclipse-foundation.org
  name: Christopher Guindon
  on:
    branch: master
    node_js: '10'
env:
  global:
    secure: V2Z1e3DPD6htK9cPVPLYsCOQXTG2MpI8uKtseWk/lfXos0XClFILRC/p5t57KAd4MMxX1Hhg55a6NlXQn5a6o6OpmoakqbVQBB9GUQuhieM8AVWHFu15UgEB8CuiLrMH1Fb2Vu853Y3xgFRYBDBlLq8AmP3lf6HLxWUD1ykhJjfZITTqrTcdWKY6IoQZp0Gk3aLAM4T1x/VWQQnWLJknP8GStBSH1k2kiPHnTR4YaS1I6sy9PfVrAZlJpzuBIVuzN5XEBu1XVP0UitQFDwzr3exnHF7HKUQrBTos5FBy6ybEJEGZdLLiYEtTdl/Wc3+bcc/fwKHWKIGM8AG2mmCaKCdgC8iXXWpIURjjZpMuiO+RF3kfHrH2scNFYEDa13HSAEtO+7wi97bt3LYgX5qMFuLJVA4y3pzG91ObcXeSoC1oEIc7c1FuSBO6IsKa/UO2/quSuBwLrLjYZzZL3tM73MYI67x+sbbSs54hLo9FaX/KgUMiZoNmZr7+bzfoGKNyfrSA2LAlg1K0bXZRQPDcW/BqIfIYwuQS242EAphXM0bMDmaC9fC98UmyS/Qvn8V5rAa5avgg7Gh3z/fdJZXNjjeOX8eTmkz6+QDXxEsS6XWZVSGFSSkzbFbAy4d2ValtfTYc6wnytK6kSysz7O60e10fpEC/KgI7yqrurhcfIvU=
