baseurl = "https://osdforum.org/"
DefaultContentLanguage = "en"
title = "OSDForum" 
theme = "eclipsefdn-hugo-solstice-theme"
metaDataFormat = "yaml"
#googleAnalytics = ""
disableKinds = ["taxonomyTerm"]
themesDir = "node_modules/"
enableRobotsTXT = true

[Params]
  google_tag_manager = "GTM-5WLCZXC"
  description = "The Open Source Developer Forum is a one day workshop that brings open source software and hardware (chips, boards and systems) developers together to collaborate and learn."
  subtitle = ""
  seo_title_suffix = " | Open Source Developer Forum | OpenHW Group"
  keywords = ["open-source", "risc-v", "hardware", "software", "hw", "sw", "eclipse ide"]
  logo = "images/logo.png"
  styles = "css/styles.css"
  favicon = "images/favicon.ico"
  share_img = "images/logo.png"
  gcse = ""
# subtheme = ""
  header_wrapper_class = "header-default-bg-img"
  js = "js/solstice.js"
# call_for_action_text = ""
# call_for_action_url = ""
# call_for_action_icon = ""
  navbar_wrapper_classes = "background-white"
  featured_content_publish_target = "openhwgroup"

[taxonomies]
  category = "categories"
  tag = "tags"

[Author]
  name = "OpenHW Group"
  website = "https://www.openhwgroup.org"
  email = "info@openhwgroup.org"
# facebook = ""
  twitter = "osdforum"
# youtube = ""
# googleplus = ""
 linkedin = "osdforum"

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
  
[[menu.main]]
  name = "Code of Conduct"
  url = "https://events.eclipse.org/code-of-conduct/"

[[menu.main]]
  name = "Past events"
  
[[menu.main]]
  name = "2019"
  url = "/2019"
  parent = "Past events"
